package net.pvp.portal.entidades;

// Generated 19/03/2014 20:53:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Candidato generated by hbm2java
 */
@Entity
@Table(name = "candidato", catalog = "pvp_db")
public class Candidato implements java.io.Serializable {

	private int codigo;
	private String nome;
	private Set<Postagem> postagems = new HashSet<Postagem>(0);
	private Set<Filiacao> filiacaos = new HashSet<Filiacao>(0);

	public Candidato() {
	}

	public Candidato(String nome) {
		this.nome = nome;
	}

	public Candidato(String nome, Set<Postagem> postagems,
			Set<Filiacao> filiacaos) {
		this.nome = nome;
		this.postagems = postagems;
		this.filiacaos = filiacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidato")
	public Set<Postagem> getPostagems() {
		return this.postagems;
	}

	public void setPostagems(Set<Postagem> postagems) {
		this.postagems = postagems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidato")
	public Set<Filiacao> getFiliacaos() {
		return this.filiacaos;
	}

	public void setFiliacaos(Set<Filiacao> filiacaos) {
		this.filiacaos = filiacaos;
	}

}
