package net.pvp.portal.entidades;

// Generated 19/03/2014 20:53:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partido generated by hbm2java
 */
@Entity
@Table(name = "partido", catalog = "pvp_db")
public class Partido implements java.io.Serializable {

	private int codigo;
	private String nome;
	private String sigla;
	private Set<Filiacao> filiacaos = new HashSet<Filiacao>(0);

	public Partido() {
	}

	public Partido(String nome, String sigla) {
		this.nome = nome;
		this.sigla = sigla;
	}

	public Partido(String nome, String sigla, Set<Filiacao> filiacaos) {
		this.nome = nome;
		this.sigla = sigla;
		this.filiacaos = filiacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "sigla", nullable = false, length = 2)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partido")
	public Set<Filiacao> getFiliacaos() {
		return this.filiacaos;
	}

	public void setFiliacaos(Set<Filiacao> filiacaos) {
		this.filiacaos = filiacaos;
	}

}
