package net.pvp.portal.entidades;

// Generated 25/03/2014 20:13:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissaoUsuarioId generated by hbm2java
 */
@Embeddable
public class PermissaoUsuarioId implements java.io.Serializable {

	private Integer codTipoUsuario;
	private Integer codPermissao;

	public PermissaoUsuarioId() {
	}

	public PermissaoUsuarioId(Integer codTipoUsuario, Integer codPermissao) {
		this.codTipoUsuario = codTipoUsuario;
		this.codPermissao = codPermissao;
	}

	@Column(name = "cod_tipo_usuario")
	public Integer getCodTipoUsuario() {
		return this.codTipoUsuario;
	}

	public void setCodTipoUsuario(Integer codTipoUsuario) {
		this.codTipoUsuario = codTipoUsuario;
	}

	@Column(name = "cod_permissao")
	public Integer getCodPermissao() {
		return this.codPermissao;
	}

	public void setCodPermissao(Integer codPermissao) {
		this.codPermissao = codPermissao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermissaoUsuarioId))
			return false;
		PermissaoUsuarioId castOther = (PermissaoUsuarioId) other;

		return ((this.getCodTipoUsuario() == castOther.getCodTipoUsuario()) || (this
				.getCodTipoUsuario() != null
				&& castOther.getCodTipoUsuario() != null && this
				.getCodTipoUsuario().equals(castOther.getCodTipoUsuario())))
				&& ((this.getCodPermissao() == castOther.getCodPermissao()) || (this
						.getCodPermissao() != null
						&& castOther.getCodPermissao() != null && this
						.getCodPermissao().equals(castOther.getCodPermissao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodTipoUsuario() == null ? 0 : this.getCodTipoUsuario()
						.hashCode());
		result = 37
				* result
				+ (getCodPermissao() == null ? 0 : this.getCodPermissao()
						.hashCode());
		return result;
	}

}
