package net.pvp.portal.entidades;

// Generated 25/03/2014 20:13:13 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.security.core.GrantedAuthority;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name = "permissao", catalog = "pvp_db")
public class Permissao implements GrantedAuthority, java.io.Serializable {

	private int codigo;
	private String nome;
	private String role;
	private Set<PermissaoUsuario> permissaoUsuarios = new HashSet<PermissaoUsuario>(
			0);

	public Permissao() {
	}

	public Permissao(final String nome, final String role) {
		this.nome = nome;
		this.role = role;
	}

	public Permissao(final String nome, final String role,
			final Set<PermissaoUsuario> permissaoUsuarios) {
		this.nome = nome;
		this.role = role;
		this.permissaoUsuarios = permissaoUsuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(final int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(final String nome) {
		this.nome = nome;
	}

	@Column(name = "role", nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(final String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissao")
	public Set<PermissaoUsuario> getPermissaoUsuarios() {
		return this.permissaoUsuarios;
	}

	public void setPermissaoUsuarios(final Set<PermissaoUsuario> permissaoUsuarios) {
		this.permissaoUsuarios = permissaoUsuarios;
	}

	@Override
	public String getAuthority() {
		return this.role;
	}

}
