package net.pvp.portal.entidades;

// Generated 19/03/2014 20:53:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PostagemAuditoria generated by hbm2java
 */
@Entity
@Table(name = "postagem_auditoria", catalog = "pvp_db")
public class PostagemAuditoria implements java.io.Serializable {

	private int codigo;
	private Integer codPostagem;
	private Integer codUsuario;
	private Integer codTipoAlteracao;
	private String valorAntigo;
	private String valorNovo;

	public PostagemAuditoria() {
	}

	public PostagemAuditoria(Integer codPostagem, Integer codUsuario,
			Integer codTipoAlteracao, String valorAntigo, String valorNovo) {
		this.codPostagem = codPostagem;
		this.codUsuario = codUsuario;
		this.codTipoAlteracao = codTipoAlteracao;
		this.valorAntigo = valorAntigo;
		this.valorNovo = valorNovo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "cod_postagem")
	public Integer getCodPostagem() {
		return this.codPostagem;
	}

	public void setCodPostagem(Integer codPostagem) {
		this.codPostagem = codPostagem;
	}

	@Column(name = "cod_usuario")
	public Integer getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(Integer codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "cod_tipo_alteracao")
	public Integer getCodTipoAlteracao() {
		return this.codTipoAlteracao;
	}

	public void setCodTipoAlteracao(Integer codTipoAlteracao) {
		this.codTipoAlteracao = codTipoAlteracao;
	}

	@Column(name = "valor_antigo")
	public String getValorAntigo() {
		return this.valorAntigo;
	}

	public void setValorAntigo(String valorAntigo) {
		this.valorAntigo = valorAntigo;
	}

	@Column(name = "valor_novo")
	public String getValorNovo() {
		return this.valorNovo;
	}

	public void setValorNovo(String valorNovo) {
		this.valorNovo = valorNovo;
	}

}
