package net.pvp.portal.entidades;

// Generated 19/03/2014 20:53:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "pvp_db")
public class Status implements java.io.Serializable {

	private int codigo;
	private String nome;
	private String descricao;
	private Set<Postagem> postagems = new HashSet<Postagem>(0);

	public Status() {
	}

	public Status(String nome) {
		this.nome = nome;
	}

	public Status(String nome, String descricao, Set<Postagem> postagems) {
		this.nome = nome;
		this.descricao = descricao;
		this.postagems = postagems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<Postagem> getPostagems() {
		return this.postagems;
	}

	public void setPostagems(Set<Postagem> postagems) {
		this.postagems = postagems;
	}

}
