package net.pvp.portal.entidades;

// Generated 19/03/2014 20:53:07 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoCargo generated by hbm2java
 */
@Entity
@Table(name = "tipo_cargo", catalog = "pvp_db")
public class TipoCargo implements java.io.Serializable {

	private int codigo;
	private String nome;
	private String descricao;

	public TipoCargo() {
	}

	public TipoCargo(String nome) {
		this.nome = nome;
	}

	public TipoCargo(String nome, String descricao) {
		this.nome = nome;
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
