package net.pvp.portal.entidades;

// Generated 25/03/2014 20:13:13 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipo_usuario", catalog = "pvp_db")
public class TipoUsuario implements java.io.Serializable {

	private int codigo;
	private String nome;
	private String descricao;
	private Set<PermissaoUsuario> permissaoUsuarios = new HashSet<PermissaoUsuario>(
			0);

	public TipoUsuario() {
	}

	public TipoUsuario(String nome) {
		this.nome = nome;
	}

	public TipoUsuario(String nome, String descricao,
			Set<PermissaoUsuario> permissaoUsuarios) {
		this.nome = nome;
		this.descricao = descricao;
		this.permissaoUsuarios = permissaoUsuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUsuario")
	public Set<PermissaoUsuario> getPermissaoUsuarios() {
		return this.permissaoUsuarios;
	}

	public void setPermissaoUsuarios(Set<PermissaoUsuario> permissaoUsuarios) {
		this.permissaoUsuarios = permissaoUsuarios;
	}

}
