package net.pvp.portal.entidades;

// Generated 19/03/2014 20:53:07 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "pvp_db", uniqueConstraints = {
		@UniqueConstraint(columnNames = "cpf"),
		@UniqueConstraint(columnNames = "login") })
public class Usuario implements java.io.Serializable {

	private int codigo;
	private TipoUsuario tipoUsuario;
	private String nome;
	private String login;
	private String senha;
	private int cpf;
	private Date dataIncricao;
	private Date dataUltimoAcesso;
	private char indAtivo;
	private Set<Postagem> postagems = new HashSet<Postagem>(0);

	public Usuario() {
	}

	public Usuario(TipoUsuario tipoUsuario, String nome, String login,
			String senha, int cpf, Date dataIncricao, char indAtivo) {
		this.tipoUsuario = tipoUsuario;
		this.nome = nome;
		this.login = login;
		this.senha = senha;
		this.cpf = cpf;
		this.dataIncricao = dataIncricao;
		this.indAtivo = indAtivo;
	}

	public Usuario(TipoUsuario tipoUsuario, String nome, String login,
			String senha, int cpf, Date dataIncricao, Date dataUltimoAcesso,
			char indAtivo, Set<Postagem> postagems) {
		this.tipoUsuario = tipoUsuario;
		this.nome = nome;
		this.login = login;
		this.senha = senha;
		this.cpf = cpf;
		this.dataIncricao = dataIncricao;
		this.dataUltimoAcesso = dataUltimoAcesso;
		this.indAtivo = indAtivo;
		this.postagems = postagems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tipo_usuario", nullable = false)
	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "nome", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "login", unique = true, nullable = false, length = 30)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "senha", nullable = false, length = 50)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "cpf", unique = true, nullable = false)
	public int getCpf() {
		return this.cpf;
	}

	public void setCpf(int cpf) {
		this.cpf = cpf;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_incricao", nullable = false, length = 19)
	public Date getDataIncricao() {
		return this.dataIncricao;
	}

	public void setDataIncricao(Date dataIncricao) {
		this.dataIncricao = dataIncricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_ultimo_acesso", length = 19)
	public Date getDataUltimoAcesso() {
		return this.dataUltimoAcesso;
	}

	public void setDataUltimoAcesso(Date dataUltimoAcesso) {
		this.dataUltimoAcesso = dataUltimoAcesso;
	}

	@Column(name = "ind_ativo", nullable = false, length = 1)
	public char getIndAtivo() {
		return this.indAtivo;
	}

	public void setIndAtivo(char indAtivo) {
		this.indAtivo = indAtivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Postagem> getPostagems() {
		return this.postagems;
	}

	public void setPostagems(Set<Postagem> postagems) {
		this.postagems = postagems;
	}

}
